### PR TITLE
Documentation

### LINKED ISSUE #31: Need package documentation.

### PR DESCRIPTION
**Pull request by ArtemKolichenkov**
Closes #31

### First commit Upgrads SDK to 28

Example app didn't even start on my emulator/device. Since AndroidX been up for 3 months already its time to upgrade SDK to 28 and enable jetifier.

New flutter version also enables R8 automatically.

### Other commits

Basicaly added bunch of doc comments for pub.dev API Reference, modified CONTRIBUTING.md, etc.

Feel free to suggest edits.

### CODE REVIEW

**Comment by ArtemKolichenkov** [comment]
I also discovered some issues worthy of discussion while writing documentation. See #42, #43, #44.

**Comment by xsahil03x** [comment]
@ArtemKolichenkov thank you so much for the documentation, and yes I checked those issues and found them worth discussing. Thanks again :+1:

**Comment by xsahil03x** [comment]
@all-contributors please add @ArtemKolichenkov  for doc

**Comment by xsahil03x** [comment]
@all-contributors please add @jakebolam for doc, ideas

**Pull request merged**
