### PR TITLE
Landscape mode added for all 3 Widgets

### PR DESCRIPTION
**Pull request by dpedrinha**

### CODE REVIEW

**Comment by xsahil03x** [comment]
Hey, @dpedrinha try to remove all the unwanted files and make sure you pass all the tests.

**Comment by dpedrinha** [comment]
Hi. I'm not a git expert. To be honest, I follow tutorials on how to do this kind of thing.

But I didn't add a single file and it's building perfectly on my end. If files were added and it's not building it's probably due to different flutter / dart / android /Java versions or IDE. I removed some deprecated stuff from the code (like 'new' statements) so I'm betting this is the problem. 

Landscape mode is working as suggested, but I'm done here. I'm not even using this plug in, I developed my own. I just stumbled upon a request to make a landscape mode the same way I did mine so I just figured I could give a hand. But I'm really bad at finding this kind of framework problems and like any other developer, I hate it. 

So we will need to wait for someone else to find out why it failed to build and edit the gitignore file. Maybe the guy asking for this feature?

Cheers!

**Comment by dpedrinha** [comment]
There. As I thought, the extra files came from the IDE (INTELIJ IDEA).

**Comment by dpedrinha** [comment]
Looks like this Travis CI is the one who needs some fixing @xsahil03x

**Comment by xsahil03x** [comment]
@dpedrinha thanks for your contribution. Cheers :+1:

**Comment by xsahil03x** [comment]
@all-contributors please add @dpedrinha  for code

**Pull request merged**
