### PR TITLE
Vertical button and onCancelCallback for 3 dialogs

### PR DESCRIPTION
**Pull request by enzoftware**
Solve to #13 issue
- Add onCancel callback
- Vertical orientation for buttons

### CODE REVIEW

**Comment by xsahil03x** [comment]
Can you share some screenshots and resolve these merge conflicts.

**Comment by enzoftware** [comment]
> Can you share some screenshots and resolve these merge conflicts.

Ok

**Comment by xsahil03x** [comment]
@enzoftware any update or should I close this PR?

**Comment by xsahil03x** [comment]
Closing as no update.

**Pull request closed without merging**
