### PR TITLE
1.imageUrl to image 2.barrierDismissible 3.format

### PR DESCRIPTION
**Pull request by xch1029**

### CODE REVIEW

**Comment by Ademking** [comment]
i confirm

**Comment by xsahil03x** [comment]
@xch1029 you also need to do changes in the source code. A package does not work just by changing the Readme files.

**Comment by xch1029** [comment]
> @xch1029 you also need to do changes in the source code. A package does not work just by changing the Readme files.

the README is out time so I update it to match the source code

**Comment by xsahil03x** [comment]
> > @xch1029 you also need to do changes in the source code. A package does not work just by changing the Readme files.
> 
> the README is out time so I update it to match the source code

Ohh, thanks for the PR then. But always write a proper title to the PR before making it.

**Comment by xch1029** [comment]
> > > @xch1029 you also need to do changes in the source code. A package does not work just by changing the Readme files.
> > 
> > 
> > the README is out time so I update it to match the source code
> 
> Ohh, thanks for the PR then. But always write a proper title to the PR before making it.

sorry. next time I'll do better

**Pull request closed without merging**
